version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: 'rabbitmq'
    ports:
        - 5673:5672
        - 15673:15672
    networks:
        - rabbitmq_go_net
    environment:
        - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-admin}
        - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-admin}

networks:
  rabbitmq_go_net:
    driver: bridge


