version: '2.2' 
services:
    nginx:
      image: nginx:latest
      ports:
            - "80:80"
            - "443:443"
      volumes:
            - ./hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
      links:
            - php
    php:
        build: ./images/php
        links:
            - mysql
            - rabbitmq
        volumes:
            - ./www:/var/www
    mysql:
        image: mysql:8
        ports:
            - "3308:3306"
        volumes:
            - ./b2b.sql:/docker-entrypoint-intidb.d
            - ./mysql:/var/lib/mysql
        container_name: 'mysql'
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_ROOT_USER: root
    rabbitmq:
        image: rabbitmq:3-management-alpine
        container_name: 'rabbitmq'
        ports:
          - 5672:5672
          - 15672:15672
        environment:
          - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER:-admin}
          - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS:-admin}

