version: '2.2'
services:
    mysql8:
      container_name: mysql8
      image: mysql:8.0.25
      command: --default-authentication-plugin=mysql_native_password --collation-server=utf8_general_ci --character-set-server=utf8 --sql_mode="" --skip-log-bin
      restart: always
      environment:
        MYSQL_ROOT_PASSWORD: root
        MYSQL_USER: user
        MYSQL_PASSWORD: user
      ports:
        - '3307:3306'
      volumes:
        - ./mysql8:/var/lib/mysql
      networks:
        - backend
    phpmyadmin:
      image: phpmyadmin:5.2.1
      depends_on:
        - mysql8
      restart: always
      ports:
        - '9090:80'
      environment:
        PMA_HOSTS: mysql8
        MYSQL_ROOT_PASSWORD: root
        PMA_PASSWORD: root
        PMA_USER: root
      networks:
        - backend
networks:
  backend:
      driver: bridge